Disables got retry logic
Disables retry logic following suggestion from https://github.com/sindresorhus/got/issues/1489 to prevent ` throw new Error('The `onCancel` handler was attached after the promise settled.')`

Doing this in the non-esm branch because I've not converted the client to ESM

```
/Users/beauraines/projects/toggl-cli-node/node_modules/p-cancelable/index.js:48
                    throw new Error('The `onCancel` handler was attached after the promise settled.');
                          ^

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/Users/beauraines/projects/toggl-cli-node/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/Users/beauraines/projects/toggl-cli-node/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/Users/beauraines/projects/toggl-cli-node/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:628:26)
    at Request.emit (node:events:513:28)
    at Timeout.retry (/Users/beauraines/projects/toggl-cli-node/node_modules/got/dist/source/core/index.js:1278:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```