ci(reports): adds unit test for each report method
Two tests are failing, but I think that is because of the pagination changes

-  should get all pages of the detailed report:
     TypeError: reportPage.data is not iterable (cannot read property undefined)

- should get all pages of the summary report:
     TypeError: reportPage.data is not iterable (cannot read property undefined)